vich_uploader:
    db_driver: orm

    mappings:
        photos:
            uri_prefix: /images/photos
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        videos:
            uri_prefix: /videos
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
