vich_uploader:
    db_driver: orm

    mappings:
        photos:
            uri_prefix: /images/photos
            upload_destination: '%kernel.project_dir%/public/images/photos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        videos:
            uri_prefix: /videos
            upload_destination: '%kernel.project_dir%/public/videos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        accueil:
            uri_prefix: /images/accueil
            upload_destination: '%kernel.project_dir%/public/images/accueil'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
